### ISSUE TITLE
Depend on upstream ruamel.yaml instead of unmaintained ruamel_yaml

### ISSUE THREAD

**Issue by mbargull** [conda-forge/faunus-feedstock#42]
### Comment:

I'm currently looking at what packages on conda-forge have a dependency on the non-maintained `ruamel_yaml` package.

It'd be good if we could have this package depend on `ruamel.yaml` instead of `ruamel_yaml`, too.

NB: The latest `conda-forge::ruamel_yaml` is still at version `0.15.80` -- upstream released that version 5 years ago.

----
Faunus uses the PyYAML top-level `yaml.safe_load`/`yaml.safe_dump` functions which have been removed in `ruamel.yaml=0.18`  (see https://pypi.org/project/ruamel.yaml/0.18.4/ for details).
I've issued an upstream PR to use the `load`/`dump` methods from `ruamel.yaml.YAML(typ="safe")` for compatibility with `ruamel.yaml=0.18` at https://github.com/mlund/faunus/pull/435 . (Though not tested by me, due to time constraints.)

It may make sense to add an upper bound on the `ruamel.yaml` dependency with `,<0.19.0a0` with the upstream PR included or `,<0.18.0a0` without.

**Comment by mlund** [comment]
Closed by #47
